# Generated by Django 4.2.29 on 2026-03-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerificationToken',
            new_name='Verification',
        ),
    ]
