# Generated by Django 4.2.29 on 2026-04-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_birth_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
